# Write your MySQL query statement below
SELECT DISTINCT AUTHOR_ID AS ID FROM VIEWS AS V WHERE EXISTS
(
SELECT 1 FROM VIEWS AS M WHERE M.VIEWER_ID=V.AUTHOR_ID AND M.ARTICLE_ID=V.ARTICLE_ID
) ORDER BY AUTHOR_ID;